name: 🔗 GHA
on: [push, pull_request, merge_group, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  # First stage: Only static checks, fast and prevent expensive builds from running.

  static-checks:
    if: ${{ false }}
    name: 📊 Static checks
    uses: ./.github/workflows/static_checks.yml

  # Second stage: Run all the builds and some of the tests.

  android-build:
    if: ${{ false }}
    name: 🤖 Android
    needs: static-checks
    uses: ./.github/workflows/android_builds.yml
    secrets:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}

  ios-build:
    if: ${{ false }}
    name: 🍏 iOS
    needs: static-checks
    uses: ./.github/workflows/ios_builds.yml

  linux-build:
    if: ${{ false }}
    name: 🐧 Linux
    needs: static-checks
    uses: ./.github/workflows/linux_builds.yml
    with:
      changed-files: ${{ needs.static-checks.outputs.changed-files }}

  macos-build:
    if: ${{ false }}
    name: 🍎 macOS
    needs: static-checks
    uses: ./.github/workflows/macos_builds.yml

  windows-build:
    if: ${{ false }}
    name: 🏁 Windows
    needs: static-checks
    uses: ./.github/workflows/windows_builds.yml

  web-build:
    if: ${{ false }}
    name: 🌐 Web
    needs: static-checks
    uses: ./.github/workflows/web_builds.yml
